name: '1min.ai Auto Checkin'
description: '1min.ai Auto Checkin GitHub Action'
author: 'Your Name'

inputs:
  email:
    description: '1min.ai account email'
    required: true
  password:
    description: '1min.ai account password'
    required: true
  totp_secret:
    description: 'TOTP secret key (if 2FA is enabled)'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'check-circle'
  color: 'green'